apiVersion: v1
kind: Namespace
metadata:
  name: app-test-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-2-deploy
  namespace: app-test-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-test-2
  template:
    metadata:
      labels:
        app: app-test-2
    spec:
      containers:
      - name: app-test-c1
        image: nginx
        ports:
        - name: web
          containerPort: 80
        securityContext:
          readOnlyRootFilesystem: false
        resources:
          requests:
            cpu: 500m
            memory: 520Mi
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-2-svc
  namespace: app-test-2
  labels:
    app: app-test-2
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    targetPort: 8082
    protocol: TCP
  selector:
    app: app-test-2
---


